# Generated by Django 5.1.5 on 2025-01-25 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("userid", models.IntegerField(unique=True)),
                ("username", models.CharField(max_length=255)),
            ],
        ),
    ]
