# Generated by Django 5.1.5 on 2025-01-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("test_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name="user",
            table="user",
        ),
    ]
