# Generated by Django 5.1.6 on 2025-02-23 14:19

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_id", models.IntegerField()),
                ("item_name", models.CharField(max_length=255)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("item_image", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(default=1)),
                ("quantity", models.IntegerField(default=1)),
                ("caution", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_login", models.DateTimeField(blank=True, null=True, verbose_name="last login")),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=150, verbose_name="first name")),
                ("last_name", models.CharField(blank=True, max_length=150, verbose_name="last name")),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                ("date_joined", models.DateTimeField(default=django.utils.timezone.now, verbose_name="date joined")),
                ("kakao_id", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("group_admin_id", models.IntegerField(blank=True, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ("username", models.CharField(max_length=20, unique=True)),
                ("profile_image", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(blank=True, related_name="shared_custom_user_groups", to="auth.group"),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True, related_name="shared_custom_user_permissions", to="auth.permission"
                    ),
                ),
            ],
            options={
                "verbose_name": "유저",
                "verbose_name_plural": "유저정보",
                "db_table": "shared_users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("reservation_date", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.user")),
            ],
        ),
        migrations.CreateModel(
            name="RentalRequest",
            fields=[
                ("request_id", models.AutoField(primary_key=True, serialize=False)),
                ("requested_at", models.DateTimeField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.user")),
            ],
        ),
        migrations.CreateModel(
            name="RentalRecord",
            fields=[
                ("rental_id", models.AutoField(primary_key=True, serialize=False)),
                ("rental_start", models.DateTimeField()),
                ("rental_end", models.DateTimeField()),
                ("actual_return", models.DateTimeField(blank=True, null=True)),
                ("rental_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.user")),
            ],
        ),
        migrations.AddField(
            model_name="item",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.user"),
        ),
    ]
