# Generated by Django 5.1.6 on 2025-02-20 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                ("group_id", models.AutoField(primary_key=True, serialize=False)),
                ("group_name", models.CharField(max_length=255)),
                ("group_type", models.CharField(max_length=50)),
                ("visibility", models.CharField(max_length=50)),
                ("group_image", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("social_id", models.CharField(max_length=255, unique=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone_number", models.CharField(max_length=20, unique=True)),
                ("nickname", models.CharField(max_length=50)),
                ("profile_image", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Item",
            fields=[
                ("item_id", models.AutoField(primary_key=True, serialize=False)),
                ("item_name", models.CharField(max_length=255)),
                ("item_description", models.TextField(blank=True, null=True)),
                ("item_image", models.TextField(blank=True, null=True)),
                ("status", models.IntegerField(default=1)),
                ("quantity", models.IntegerField(default=1)),
                ("caution", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.group")),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("book_id", models.AutoField(primary_key=True, serialize=False)),
                ("book_date", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=50)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.user")),
            ],
        ),
        migrations.CreateModel(
            name="RentalRecord",
            fields=[
                ("rental_id", models.AutoField(primary_key=True, serialize=False)),
                ("rental_start", models.DateTimeField()),
                ("rental_end", models.DateTimeField()),
                ("actual_return", models.DateTimeField(blank=True, null=True)),
                ("rental_status", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.user")),
            ],
        ),
        migrations.AddField(
            model_name="group",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.user"),
        ),
    ]
