# Generated by Django 5.1.6 on 2025-02-16 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.IntegerField()),
                ("group_name", models.CharField(max_length=255)),
                ("item_id", models.IntegerField(unique=True)),
                ("item_name", models.CharField(max_length=255)),
                ("item_description", models.TextField()),
                ("item_image", models.URLField()),
                ("status", models.IntegerField()),
                ("quantity", models.IntegerField()),
                ("caution", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Pickup",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField()),
                ("pickup_time", models.DateTimeField()),
                ("image", models.URLField()),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField()),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
            ],
        ),
        migrations.CreateModel(
            name="Return",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_id", models.IntegerField()),
                ("return_time", models.DateTimeField()),
                ("return_image", models.URLField()),
                ("item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shared.item")),
            ],
        ),
    ]
