# Generated by Django 5.1.6 on 2025-02-23 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="rentalrecord",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="rentalrecord",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="rentalrequest",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="rentalrequest",
            old_name="user_id",
            new_name="user",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="item_id",
            new_name="item",
        ),
        migrations.RenameField(
            model_name="reservation",
            old_name="user_id",
            new_name="user",
        ),
    ]
