name: WeShare CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: hwangjiwon
          POSTGRES_PASSWORD: 1234
          POSTGRES_DB: weshare

        ports:
          - 5432:5432

        options: >-
          --health-cmd="pg_isready"
          --health-interval="10s"
          --health-timeout="5s"
          --health-retries="5"

    steps:
      - name: Check out the codes
        uses: actions/checkout@v2

      - name: Setup python environment
        id: setup-python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Set timezone to KST
        run: |
          sudo rm /etc/localtime
          sudo ln -s /usr/share/zoneinfo/Asia/Seoul /etc/localtime 

      - name: Set environment variables
        run: echo "SECRET_KEY=django-insecure-j2tp%da55l^wx3xv^sm1a6eruhy@)5$3y75x=8@(e%e0fmr=^5" >> $GITHUB_ENV

          
      - name: Install Poetry
        run: |
          curl -sSL curl -sSL https://install.python-poetry.org | python3 -
          echo "${HOME}/.local/bin" >> $GITHUB_PATH

      - name: Install dependencies
        working-directory: ${{ github.workspace }}
        run: |
          poetry install --no-root

      - name: Install dependencies
        run: |
          poetry install --no-root

      - name: Run black
        run: |
          poetry run black . --check

      - name: Run isort
        run: |
          poetry run isort . --check --diff

      - name: Run Mypy
        run: |
          PYTHONPATH=$PWD poetry run mypy .


      - name: Test python project
        run: |
          poetry run python manage.py test
